### ISSUE TITLE
Allow npm installation in parent directory

### ISSUE THREAD

**Issue by schmengler** [hyva-themes/hyva-modules-tailwind-js#3]
## Use case:

a single npm installation in `app/design/frontend` or `app/design/frontend/[vendor]` for shops with multiple Hyvä based themes.

## Issue

Relative path to `app/etc/hyva-themes.json` is hard coded, so it is not taken into account (everything else works fine)

https://github.com/hyva-themes/hyva-modules-tailwind-js/blob/main/src/index.js#L12-L17

## Proposed solution

Dynamically determine path by going up in the file system until `app/etc` is found.

**Comment by Vinai** [comment]
Do you install all the other npm dependencies of a theme outside of the web/tailwind folder, too?

**Comment by schmengler** [comment]
@Vinai yes, we use a single `package.json` in those cases

**Comment by Vinai** [comment]
That makes sense then! Thanks for explaining!

**Comment by Vinai** [comment]
Released in 1.0.6
